Fixes table layout
kognifai/PoseidonNext-Framework pull request #1
Opened 2018-07-17 08:45 UTC by mgrzyb

Removes an extra (fourth) column in the Settings Service description

2018-07-17 08:51 UTC, cristianiorga requested changes
Can you please remove it from the statistics service as well?

2018-07-17 08:51 UTC, cristianiorga commented on README.md
>   Statistics Service |  [Statistics Service](PoseidonNext-documentation/SDK-reference/Statistics-Service.md)|The primary purpose of this service is to collect information pertinent to various trackabl
Can you please remove it from the statistics service as well?

2018-07-17 13:28 UTC, mgrzyb commented on README.md
>   Statistics Service |  [Statistics Service](PoseidonNext-documentation/SDK-reference/Statistics-Service.md)|The primary purpose of this service is to collect information pertinent to various trackabl
Statistics Service row looks good to me - the table has 3 columns. The problem with Settings Service was that it had 4 columns.

2018-07-19 08:34 UTC, cristianiorga approved these changes

2018-07-19 08:35 UTC, merged